# Generated by Django 3.0.5 on 2020-05-02 19:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppco2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculation',
            name='a1',
            field=models.PositiveIntegerField(default=5000, verbose_name='Plane'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='a2',
            field=models.PositiveIntegerField(default=100, verbose_name='Train'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='a3',
            field=models.PositiveIntegerField(default=1000, verbose_name='Bus'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='a4',
            field=models.PositiveIntegerField(default=5000, verbose_name='Car'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='a5',
            field=models.PositiveIntegerField(default=5000, verbose_name='Moto'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='b1',
            field=models.PositiveSmallIntegerField(default=120, help_text='(e.g. socks, undies...)', verbose_name='Small'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='b2',
            field=models.PositiveSmallIntegerField(default=48, help_text='(e.g. t-shirts, dresses...)', verbose_name='Medium'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='b3',
            field=models.PositiveSmallIntegerField(default=6, help_text='(e.g. jeans, coats...)', verbose_name='Large'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='c1',
            field=models.PositiveSmallIntegerField(default=10, help_text='(e.g. earphones, computer mouse...)', verbose_name='X Small'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='c2',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Users'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='c3',
            field=models.PositiveSmallIntegerField(default=10, help_text='(e.g. kettle, toaster, iron, speakers...)', verbose_name='Small'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='c4',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Users'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='c5',
            field=models.PositiveSmallIntegerField(default=20, help_text='(e.g. laptop, monitor, small fridge...)', verbose_name='Medium'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='c6',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Users'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='c7',
            field=models.PositiveSmallIntegerField(default=10, help_text='(e.g. washing machine, large fridge...)', verbose_name='Large'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='c8',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Users'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='d1',
            field=models.PositiveSmallIntegerField(default=200, verbose_name='Beef'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='d2',
            field=models.PositiveSmallIntegerField(default=200, verbose_name='Pork'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='d3',
            field=models.PositiveSmallIntegerField(default=200, verbose_name='Chicken'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='d4',
            field=models.PositiveSmallIntegerField(default=200, verbose_name='Fish'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='d5',
            field=models.PositiveSmallIntegerField(default=100, verbose_name='Cheese'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='d6',
            field=models.PositiveSmallIntegerField(default=100, help_text='(e.g. milk, yogurt, ice-cream...)', verbose_name='Dairy'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='d7',
            field=models.PositiveSmallIntegerField(default=14, verbose_name='Eggs (ea)'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='d8',
            field=models.PositiveSmallIntegerField(default=2000, verbose_name='Grains, Veges and Fruit'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='d9',
            field=models.PositiveSmallIntegerField(choices=[(0, 'None (0%)'), (25, 'Some (25%)'), (50, 'Half (50%)'), (75, 'Mostly (75%)'), (100, 'All (100%)')], default=75, help_text='(e.g. unprocessed or minimally processed food from wet market)', verbose_name='LOCAL food (<500km)'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='da',
            field=models.PositiveSmallIntegerField(choices=[(0, 'None (0%)'), (25, 'Some (25%)'), (50, 'Half (50%)'), (75, 'Mostly (75%)'), (100, 'All (100%)')], default=25, help_text='(e.g. processed food from Thailand or China)', verbose_name='NEAR Imported (<5000km)'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='db',
            field=models.PositiveSmallIntegerField(choices=[(0, 'None (0%)'), (25, 'Some (25%)'), (50, 'Half (50%)'), (75, 'Mostly (75%)'), (100, 'All (100%)')], default=0, help_text='(e.g. imported from Europe, Australia, US...)', verbose_name='FAR Imported (5000+km)'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='e3',
            field=models.PositiveSmallIntegerField(default=1, help_text='(family or roommates living in the same space, including yourself.)', verbose_name='Q4 - How many people do you share your living space and your electricity bill with?'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='offset',
            field=models.PositiveIntegerField(default=0, help_text='In tonnes', verbose_name='How much did you offset in the last 12 months?'),
        ),
    ]
