# Generated by Django 3.0.5 on 2020-04-16 06:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppco2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculation',
            name='a1',
            field=models.PositiveIntegerField(default=10000, verbose_name='Q1 - How far have you flown by plane in the last 12 months? (km)'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='a2',
            field=models.PositiveIntegerField(default=100, verbose_name='Q2 - How far have you taken trains in the last 12 months? (km)'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='a3',
            field=models.PositiveIntegerField(default=1000, verbose_name='Q3 - How far have you taken buses in the last 12 months? (km)'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='a4',
            field=models.PositiveIntegerField(default=5000, verbose_name='Q4 - How far have you taken cars in the last 12 months? (km)'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='a5',
            field=models.PositiveIntegerField(default=5000, verbose_name='Q5 - How far have you taken motos in the last 12 months? (km)'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='b1',
            field=models.PositiveSmallIntegerField(default=120, verbose_name='Q1 - How many small items (socks, undies) have you purchased in the last 12 months?'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='b2',
            field=models.PositiveSmallIntegerField(default=48, verbose_name='Q2 - How many medium size items (t-shirts, dresses) have you purchased in the last 12 months?'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='b3',
            field=models.PositiveSmallIntegerField(default=6, verbose_name='Q3 - How many large items (jeans, coats)?'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='c1',
            field=models.PositiveSmallIntegerField(default=6, verbose_name='Q1 - How many very small appliance (earphones, computer mouse..) have you purchased in the last 12 months?'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='c2',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Q2 - How many users do they have?'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='c3',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Q3 - How many small household appliance (kettle, toaster, iron, speakers...) have you purchased in the last 12 months?'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='c4',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Q4 - How many users do they have?'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='c5',
            field=models.PositiveSmallIntegerField(default=20, verbose_name='Q5 - How many medium-sized appliances (laptop, monitor, small fridge, desktop computer) have you purchased in the last 12 months?'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='c6',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Q6 - How many users do they have?'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='c7',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='Q7 - Large appliances (washing machine, large fridge..)'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='c8',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Q8 - How many users do they have?'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='d1',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='Q1 - How many grams of beef do you eat per week?'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='d2',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='Q2 - How many grams of pork do you eat per week?'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='d3',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='Q3 - How many grams of chicken do you eat per week?'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='d4',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='Q4 - How many grams of fish do you eat per week?'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='d5',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Q5 - How many grams of cheese do you eat per week?'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='d6',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Q6 - How many grams of milk, yogurt, ice-cream, do you eat per week?'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='d7',
            field=models.PositiveSmallIntegerField(default=21, verbose_name='Q7 - How many eggs do you eat per week?'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='d8',
            field=models.PositiveSmallIntegerField(default=3, verbose_name='Q8 - How many grams of grains, vegetables, and fruit do you eat per week?'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='d9',
            field=models.PositiveSmallIntegerField(choices=[(0, 'None'), (25, 'Some'), (50, 'Half'), (75, 'Mostly'), (100, 'All')], default=75, verbose_name='Q9 - How much of your food comes from within 500 km (e.g. unprocessed or minimally processed food from wet market)?'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='da',
            field=models.PositiveSmallIntegerField(choices=[(0, 'None'), (25, 'Some'), (50, 'Half'), (75, 'Mostly'), (100, 'All')], default=25, verbose_name='Q10 - How much of your food comes from 500-5000 km away (e.g. processed food from Thailand or China)?'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='db',
            field=models.PositiveSmallIntegerField(choices=[(0, 'None'), (25, 'Some'), (50, 'Half'), (75, 'Mostly'), (100, 'All')], default=0, verbose_name='Q11 - How much of your food comes from more than 5000 km away (imported from Europe, Australia, US..)'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='e1',
            field=models.PositiveSmallIntegerField(choices=[(0, 'None'), (25, 'Some'), (50, 'Half'), (75, 'Mostly'), (100, 'All')], default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Q1 - How much of your electricity needs are covered by your solar panels?'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='e2',
            field=models.FloatField(default=50, verbose_name='Q2 - How much is your monthly electricity bill? (USD)'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='e3',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Q3 - How many people do you share your living space and your electricity bill with (family or roommates living in the same space)?'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='e4',
            field=models.PositiveSmallIntegerField(default=8, validators=[django.core.validators.MaxValueValidator(24), django.core.validators.MinValueValidator(0)], verbose_name='Q4 - How many hours per day do you spend in air-conditioning outside of your home (e.g. office, coffee shop)'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='e5',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Q5 - Roughly how many people share this in total (including yourself. E.g. crowded coffee shop with 20 people, or small office with 4 people)?'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='f1',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='Q1 - How old is your house? (in years)'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='f2',
            field=models.PositiveSmallIntegerField(default=20, verbose_name='Q2 - How long do you think the house will be around? (in years)'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='f3',
            field=models.PositiveSmallIntegerField(default=50, verbose_name='Q3 - How big is your house, in square meters?'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='f4',
            field=models.PositiveSmallIntegerField(choices=[(100, 'Bricks and concrete'), (10, 'Wood')], default=100, verbose_name='Q4 - What is your house primarily made of?'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='f5',
            field=models.PositiveSmallIntegerField(default=4, verbose_name='Q5 - How many people live in the house on average per year?'),
        ),
    ]
