# Generated by Django 3.0.5 on 2020-04-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppco2', '0002_auto_20200416_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculation',
            name='cfp',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calculation',
            name='planets',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calculation',
            name='a1',
            field=models.PositiveIntegerField(default=5000, verbose_name='Q1 - How far have you flown by plane in the last 12 months? (km)'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='d1',
            field=models.PositiveSmallIntegerField(default=200, verbose_name='Q1 - How many grams of beef do you eat per week?'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='d2',
            field=models.PositiveSmallIntegerField(default=200, verbose_name='Q2 - How many grams of pork do you eat per week?'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='d3',
            field=models.PositiveSmallIntegerField(default=200, verbose_name='Q3 - How many grams of chicken do you eat per week?'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='d4',
            field=models.PositiveSmallIntegerField(default=200, verbose_name='Q4 - How many grams of fish do you eat per week?'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='d5',
            field=models.PositiveSmallIntegerField(default=100, verbose_name='Q5 - How many grams of cheese do you eat per week?'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='d6',
            field=models.PositiveSmallIntegerField(default=100, verbose_name='Q6 - How many grams of milk, yogurt, ice-cream, do you eat per week?'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='d7',
            field=models.PositiveSmallIntegerField(default=14, verbose_name='Q7 - How many eggs do you eat per week?'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='d8',
            field=models.PositiveSmallIntegerField(default=300, verbose_name='Q8 - How many grams of grains, vegetables, and fruit do you eat per week?'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='name',
            field=models.CharField(blank=True, default='Anonymous PP-er', max_length=30),
        ),
    ]
