# Generated by Django 3.0.5 on 2020-04-19 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppco2', '0003_auto_20200418_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculation',
            name='c1',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='Q1 - How many very small appliance (earphones, computer mouse..) have you purchased in the last 12 months?'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='c3',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='Q3 - How many small household appliance (kettle, toaster, iron, speakers...) have you purchased in the last 12 months?'),
        ),
    ]
