# Generated by Django 3.0.5 on 2020-04-22 16:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppco2', '0004_auto_20200419_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculation',
            name='e6',
            field=models.PositiveSmallIntegerField(default=800, validators=[django.core.validators.MinValueValidator(500), django.core.validators.MaxValueValidator(4000)], verbose_name='What rate do you pay for electricity? (KHR/kWh)'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='d3',
            field=models.PositiveSmallIntegerField(default=200, help_text='(On average, Americans eat 500 g of chicken per week.)', verbose_name='Q3 - How many grams of chicken do you eat per week?'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='d9',
            field=models.PositiveSmallIntegerField(choices=[(0, 'None (0%)'), (25, 'Some (25%)'), (50, 'Half (50%)'), (75, 'Mostly (75%)'), (100, 'All (100%)')], default=75, verbose_name='Q9 - How much of your food comes from within 500 km (e.g. unprocessed or minimally processed food from wet market)?'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='da',
            field=models.PositiveSmallIntegerField(choices=[(0, 'None (0%)'), (25, 'Some (25%)'), (50, 'Half (50%)'), (75, 'Mostly (75%)'), (100, 'All (100%)')], default=25, verbose_name='Q10 - How much of your food comes from 500-5000 km away (e.g. processed food from Thailand or China)?'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='db',
            field=models.PositiveSmallIntegerField(choices=[(0, 'None (0%)'), (25, 'Some (25%)'), (50, 'Half (50%)'), (75, 'Mostly (75%)'), (100, 'All (100%)')], default=0, verbose_name='Q11 - How much of your food comes from more than 5000 km away (imported from Europe, Australia, US..)'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='e1',
            field=models.PositiveSmallIntegerField(choices=[(0, 'None (0%)'), (25, 'Some (25%)'), (50, 'Half (50%)'), (75, 'Mostly (75%)'), (100, 'All (100%)')], default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Q1 - How much of your electricity needs are covered by your solar panels?'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='e5',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Q5 - Roughly how many people share this in total (including yourself. E.g. crowded coffee shop with 20 people, or small office with 4 people)?'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='f3',
            field=models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Q3 - How big is your house, in square meters?'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='f4',
            field=models.PositiveSmallIntegerField(choices=[(1000, 'Bricks and concrete'), (0, 'Wood')], default=1000, verbose_name='Q4 - What is your house primarily made of?'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='f5',
            field=models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Q5 - How many people live in the house on average per year?'),
        ),
    ]
