# Generated by Django 3.0.5 on 2020-04-22 16:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppco2', '0006_auto_20200422_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculation',
            name='f1',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='Q2 - How old is your house? (in years)'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='f2',
            field=models.PositiveSmallIntegerField(default=20, verbose_name='Q3 - How long do you think the house will be around? (in years)'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='f3',
            field=models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Q4 - How big is your house, in square meters?'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='f4',
            field=models.PositiveSmallIntegerField(choices=[(1000, 'Bricks and concrete'), (0, 'Wood')], default=1000, verbose_name='Q1 - What is your house primarily made of?'),
        ),
    ]
