# Generated by Django 3.0.5 on 2020-04-23 08:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppco2', '0009_auto_20200423_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculation',
            name='e4',
            field=models.PositiveSmallIntegerField(default=8, help_text='(e.g. office, coffee shop...)', validators=[django.core.validators.MaxValueValidator(24), django.core.validators.MinValueValidator(0)], verbose_name='Q5 - How many hours per day do you spend in air-conditioning outside of your home?'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='f3',
            field=models.PositiveSmallIntegerField(default=50, help_text='(in m<sup>2</sup>)', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Q4 - How big is your house?'),
        ),
    ]
